exports.Models = {
  BaseObject: require('./base').BaseObject,
  IncludedBaseObject: require('./base').IncludedBaseObject,
  User: require('./user').User,
  Team: require('./team').Team,
  Survey: require('./survey').Survey,
  ScoreItem: require('./score').ScoreItem,
  FloorItem: require('./score').FloorItem,
  Performer: require('./score').Performer,
  ScoreSegment: require('./score').ScoreSegment,
  FloorSegment: require('./score').FloorSegment,
  Part: require('./score').Part,
  Score: require('./score').Score,
  Block: require('./publication').Block,
  Page: require('./publication').Page,
  Section: require('./publication').Section,
  Publication: require('./publication').Publication,
  Post: require('./project').Post,
  Discussion: require('./project').Discussion,
  Project: require('./project').Project,
  Media: require('./media').Media,
  Layout: require('./layout').Layout
}